<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Receipt - {{ $txnid }}</title>
  <style>
    body { font-family: DejaVu Sans, Arial, Helvetica, sans-serif; color: #111; }
    .header { text-align: center; margin-bottom: 20px; }
    .box { border: 1px solid #ddd; padding: 16px; border-radius: 6px; }
    .two-col { display:flex; justify-content:space-between; margin-top:12px; }
    .small { font-size: 12px; color: #666; }
  </style>
</head>
<body>
  <div class="header">
    <h2>GOFX — Payment Receipt</h2>
    <div class="small">Transaction ID: {{ $txnid }} | Date: {{ $date }}</div>
  </div>

  <div class="box">
    <h3>Payment Details</h3>
    <div class="two-col">
      <div>
        <strong>Buyer</strong><br>
        {{ $name }}<br>
        {{ $email }}<br>
        {{ $phone ?? '' }}
      </div>
      <div style="text-align:right">
        <strong>Amount</strong><br>
        {{ $amount }}<br>
        <small class="small">Course: {{ $course }}</small>
      </div>
    </div>

    <div style="margin-top:14px">
      <strong>Status:</strong> {{ $status }}<br>
      <strong>Notes:</strong> This is an autogenerated receipt by GOFX.
    </div>
  </div>
</body>
</html>
